package clinicmanagementsystem.gui.admin;

import javax.swing.table.DefaultTableModel;

public class AppointmentDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppointmentDialog.class.getName());
    private DefaultTableModel model = new DefaultTableModel();
    private String[] columnList = {"AppointmentID", "Patient", "Doctor", "NurseID", "Date", "Time", "Status", "Type"};

    private String filterType;

    public AppointmentDialog(java.awt.Frame parent, boolean modal) {
        this(parent, modal, "All");
    }

    public AppointmentDialog(java.awt.Frame parent, boolean modal, String filterType) {
        super(parent, modal);
        this.filterType = filterType;
        model.setColumnIdentifiers(columnList);
        initComponents();
        clinicmanagementsystem.util.UIUtils.styleButtons(this);
        jLabel1.setText(filterType + " Appointments");
        loadAppointments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("View All Doctor");

        jTable1.setModel(model);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String getUserName(String userId) {
        if (userId.equals("N/A") || userId.isEmpty()) return "N/A";
        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader("src/clinicmanagementsystem/data/users.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.trim().isEmpty()) continue;
                String[] parts = line.split(",");
                if (parts[0].equalsIgnoreCase(userId) && parts.length > 1) {
                    return parts[1];
                }
            }
        } catch (java.io.IOException e) {}
        return userId;
    }

    private String getPatientName(String patientId) {
        if (patientId.equals("N/A") || patientId.isEmpty()) return "N/A";
        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader("src/clinicmanagementsystem/data/patients.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.trim().isEmpty()) continue;
                String[] parts = line.split(",");
                if (parts[0].equalsIgnoreCase(patientId) && parts.length > 1) {
                    return parts[1];
                }
            }
        } catch (java.io.IOException e) {}
        return patientId;
    }

    public void loadAppointments() {
        model.setRowCount(0);
        String todayStr = java.time.LocalDate.now().toString();
        try {
            String[] lines = clinicmanagementsystem.util.FileManager.readLines("src/clinicmanagementsystem/data/appointments.txt");
            for (String line : lines) {
                if (line.trim().isEmpty()) {
                    continue;
                }
                String[] parts = line.split(",");
                if (parts.length > 6) {
                    boolean add = false;
                    if (filterType.equalsIgnoreCase("All")) {
                        add = true;
                    } else if (filterType.equalsIgnoreCase("Today")) {
                        if (parts[4].trim().equals(todayStr)) {
                            add = true;
                        }
                    } else if (filterType.equalsIgnoreCase("Completed")) {
                        if (parts[7].trim().equalsIgnoreCase("Completed")) {
                            add = true;
                        }
                    } else if (filterType.equalsIgnoreCase("Cancelled")) {
                        if (parts[7].trim().equalsIgnoreCase("Cancelled")) {
                            add = true;
                        }
                    }
                    if (add) {
                        model.addRow(new Object[]{
                            parts[0], 
                            getPatientName(parts[1]), 
                            getUserName(parts[2]), 
                            getUserName(parts[3]), 
                            parts[4], parts[5], parts[7], parts[6]
                        });
                    }
                }
            }
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AppointmentDialog dialog = new AppointmentDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
