package clinicmanagementsystem.gui.admin;

import clinicmanagementsystem.gui.AdminDashboardGUI;
import clinicmanagementsystem.util.FileManager;
import javax.swing.table.DefaultTableModel;

public class ManageUserGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageUserGUI.class.getName());
    private DefaultTableModel model = new DefaultTableModel();
    private String[] columnList = {"ID", "FullName", "Gender", "PhoneNo", "Email", "UserName", "Password", "Role"};
    private int row = -1; // -1 is used to indicate no row selected in the beginning

    /**
     * Creates new form ManageUserGUI
     */
    public ManageUserGUI() {
        model.setColumnIdentifiers(columnList);
        loadDataToTable("src/clinicmanagementsystem/data/users.txt");
        initComponents();
        clinicmanagementsystem.util.UIUtils.styleButtons(this);
    }

    public void loadDataToTable(String fileName) {
        FileManager.loadDataToTable(fileName, model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AddButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        clearBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("PhoneNo");

        jLabel3.setText("FullName");

        jLabel4.setText("Gender");

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jTable1.setModel(model);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        AddButton.setText("Add");
        AddButton.addActionListener(this::AddButtonActionPerformed);

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(this::DeleteButtonActionPerformed);

        EditButton.setText("Edit");
        EditButton.addActionListener(this::EditButtonActionPerformed);

        jLabel5.setText("Email");

        jLabel6.setText("UserName");

        jLabel7.setText("Role");

        jLabel8.setText("Password");

        jTextField8.addActionListener(this::jTextField8ActionPerformed);

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel9.setText("Manage User");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "doctor", "nurse", "receptionist" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));

        clearBtn.setText("Clear");
        clearBtn.addActionListener(this::clearBtnActionPerformed);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jTextField2.setText("Search with UserID");

        searchBtn.setText("Search");
        searchBtn.addActionListener(this::searchBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(EditButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DeleteButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(clearBtn)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(179, 179, 179))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(205, 205, 205))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(jLabel9))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(searchBtn)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(785, 785, 785)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel5))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(19, 19, 19)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(AddButton)
                                            .addComponent(EditButton))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(DeleteButton)
                                            .addComponent(clearBtn)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14)
                                .addComponent(backButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        AdminDashboardGUI adminDashboard = new AdminDashboardGUI();
        adminDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        row = jTable1.getSelectedRow();

        String id = model.getValueAt(row, 0) != null ? model.getValueAt(row, 0).toString() : "";
        String name = model.getValueAt(row, 1) != null ? model.getValueAt(row, 1).toString() : "";
        String gender = model.getValueAt(row, 2) != null ? model.getValueAt(row, 2).toString() : "";
        String phone = model.getValueAt(row, 3) != null ? model.getValueAt(row, 3).toString() : "";
        String email = model.getValueAt(row, 4) != null ? model.getValueAt(row, 4).toString() : "";
        String username = model.getValueAt(row, 5) != null ? model.getValueAt(row, 5).toString() : "";
        String password = model.getValueAt(row, 6) != null ? model.getValueAt(row, 6).toString() : "";
        String role = model.getValueAt(row, 7) != null ? model.getValueAt(row, 7).toString() : "";

        jTextField4.setText(id);
        jTextField1.setText(name);
        jComboBox2.setSelectedItem(gender.toLowerCase());
        jTextField3.setText(phone);
        jTextField5.setText(email);
        jTextField6.setText(username);
        jTextField8.setText(password);
        jComboBox1.setSelectedItem(role.toLowerCase());
    }//GEN-LAST:event_jTable1MouseReleased

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        clearAllTextFields();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String searchId = jTextField2.getText().trim();

        // If search box is empty or default placeholder, load all records back
        if (searchId.isEmpty() || searchId.equalsIgnoreCase("Search with UserID")) {
            model.setRowCount(0);
            loadDataToTable("src/clinicmanagementsystem/data/users.txt");
            return;
        }

        // Clear current rows and read directly from file to look for matches
        model.setRowCount(0);
        try {
            String[] lines = FileManager.readLines("src/clinicmanagementsystem/data/users.txt");
            boolean found = false;

            for (String line : lines) {
                String[] parts = line.split(",", -1);
                if (parts.length < 8) {
                    String[] padded = new String[8];
                    for (int i = 0; i < 8; i++) padded[i] = (i < parts.length) ? parts[i] : "";
                    parts = padded;
                }
                // parts[0] contains the User ID
                if (parts[0].equalsIgnoreCase(searchId)) {
                    model.addRow(parts);
                    found = true;
                }
            }

            if (!found) {
                javax.swing.JOptionPane.showMessageDialog(this, "No user found for ID: " + searchId);
                // Reload all if nothing found
                loadDataToTable("src/clinicmanagementsystem/data/users.txt");
                jTextField2.setText("");
            }
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        String id = jTextField4.getText().trim();
        String name = jTextField1.getText().trim();
        String gender = jComboBox2.getSelectedItem() != null ? jComboBox2.getSelectedItem().toString() : "";
        String phone = jTextField3.getText().trim();
        String email = jTextField5.getText().trim();
        String username = jTextField6.getText().trim();
        String password = jTextField8.getText().trim();
        String role = jComboBox1.getSelectedItem() != null ? jComboBox1.getSelectedItem().toString() : "";

        if (id.isEmpty() || name.isEmpty() || gender.isEmpty() || phone.isEmpty() || email.isEmpty() || username.isEmpty() || password.isEmpty() || role.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "All fields must be filled!");
            return;
        }
        // checking duplicate with ID
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).toString().trim().equals(id.trim())) {
                javax.swing.JOptionPane.showMessageDialog(this, "User ID already exists! Please use a unique ID.");
                return;
            }
        }

        // Standardize format: Capitalize first letter
        gender = gender.substring(0, 1).toUpperCase() + gender.substring(1).toLowerCase();
        role = role.substring(0, 1).toUpperCase() + role.substring(1).toLowerCase();

        String newLine = id + "," + name + "," + gender + "," + phone + "," + email + "," + username + "," + password + "," + role;

        try {
            FileManager.appendLine("src/clinicmanagementsystem/data/users.txt", newLine);
            String[] rowData = {id, name, gender, phone, email, username, password, role};
            model.addRow(rowData);
            clearAllTextFields();
            javax.swing.JOptionPane.showMessageDialog(this, "User added successfully!");
        } catch (java.io.IOException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error adding user.");
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a user from the table to delete!");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this user?", "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // 1. Remove the row from the table model
            model.removeRow(row);

            // 2. Rewrite the updated model back to the file
            FileManager.rewriteFile("src/clinicmanagementsystem/data/users.txt", model);

            // 3. Reset GUI
            clearAllTextFields();
            row = -1; // Reset selection

            javax.swing.JOptionPane.showMessageDialog(this, "User deleted successfully!");
        }
    }

    private void clearAllTextFields() {
        jTextField1.setText("");
        if (jComboBox2.getItemCount() > 0) {
            jComboBox2.setSelectedIndex(0);
        }
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField8.setText("");
        if (jComboBox1.getItemCount() > 0) {
            jComboBox1.setSelectedIndex(0);
        }
        jTextField2.setText(""); // clear search box
        row = -1;
        model.setRowCount(0);
        loadDataToTable("src/clinicmanagementsystem/data/users.txt");
    }//GEN-LAST:event_DeleteButtonActionPerformed


    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a user from the table to edit!");
            return;
        }

        String newId = jTextField4.getText().trim();
        String newName = jTextField1.getText().trim();
        String newGender = jComboBox2.getSelectedItem() != null ? jComboBox2.getSelectedItem().toString() : "";
        String newPhone = jTextField3.getText().trim();
        String newEmail = jTextField5.getText().trim();
        String newUsername = jTextField6.getText().trim();
        String newPassword = jTextField8.getText().trim();
        String newRole = jComboBox1.getSelectedItem() != null ? jComboBox1.getSelectedItem().toString() : "";

        if (newId.isEmpty() || newName.isEmpty() || newGender.isEmpty() || newPhone.isEmpty() || newEmail.isEmpty() || newUsername.isEmpty() || newPassword.isEmpty() || newRole.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "All fields must be filled!");
            return;
        }

        newGender = newGender.substring(0, 1).toUpperCase() + newGender.substring(1).toLowerCase();
        newRole = newRole.substring(0, 1).toUpperCase() + newRole.substring(1).toLowerCase();

        model.setValueAt(newId, row, 0);
        model.setValueAt(newName, row, 1);
        model.setValueAt(newGender, row, 2);
        model.setValueAt(newPhone, row, 3);
        model.setValueAt(newEmail, row, 4);
        model.setValueAt(newUsername, row, 5);
        model.setValueAt(newPassword, row, 6);
        model.setValueAt(newRole, row, 7);

        FileManager.rewriteFile("src/clinicmanagementsystem/data/users.txt", model);
        clearAllTextFields();
        row = -1; // Reset selection
        javax.swing.JOptionPane.showMessageDialog(this, "User updated successfully!");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageUserGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
}
