/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicmanagementsystem.gui.nurse;

import clinicmanagementsystem.util.FileManager;
import clinicmanagementsystem.util.ValidationUtil;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class UpdateAppointmentStatus extends javax.swing.JFrame {
    private static final String APPOINTMENTS_FILE = "src/clinicmanagementsystem/data/appointments.txt";
    private static final String PATIENTS_FILE     = "src/clinicmanagementsystem/data/patients.txt";

    private static final String[] STATUS_OPTIONS = { "Scheduled", "Ongoing", "Completed" };

    /**
     * Creates new form StatusForm
     */
    public UpdateAppointmentStatus() {
        initComponents();
        clinicmanagementsystem.util.UIUtils.styleButtons(this);
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(STATUS_OPTIONS));
        
        txtApptId.setText("Enter Appt ID...");
        txtApptId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtApptId.getText().equals("Enter Appt ID...")) txtApptId.setText("");
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtApptId.getText().isEmpty()) txtApptId.setText("Enter Appt ID...");
            }
        });
    }

    /** Look up a patient name from patients.txt; falls back to the id. */
    private String patientName(String patientId) {
        try {
            String[] lines = FileManager.readLines(PATIENTS_FILE);
            for (String line : lines) {
                if (line == null) continue;
                String[] p = line.split(",");
                if (p.length >= 2 && p[0].equalsIgnoreCase(patientId)) return p[1];
            }
        } catch (IOException ex) {
            // ignore
        }
        return patientId;
    }

    /** Look up a doctor name from users.txt; falls back to the id. */
    private String doctorName(String doctorId) {
        try {
            String[] lines = FileManager.readLines("src/clinicmanagementsystem/data/users.txt");
            for (String line : lines) {
                if (line == null) continue;
                String[] u = line.split(",");
                if (u.length >= 2 && u[0].equalsIgnoreCase(doctorId)) return u[1];
            }
        } catch (IOException ex) {
            // ignore
        }
        return doctorId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbStatus = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        txtApptId = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblPatient = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDoctor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbStatus.addActionListener(this::cmbStatusActionPerformed);

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        jLabel1.setText("Patient Name:");

        jLabel2.setText("Date:");

        jLabel3.setText("Time:");

        jLabel4.setText("Doctor:");

        jLabel5.setText("Status");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Update Appointment Status");

        jLabel7.setText("Search with Appointment ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDate)
                            .addComponent(lblPatient)
                            .addComponent(lblTime)
                            .addComponent(lblDoctor))
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSave)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtApptId, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPatient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDate))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtApptId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTime)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDoctor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String id = txtApptId.getText().trim();
        if (id.isEmpty() || id.equalsIgnoreCase("Enter Appt ID...")) {   // ignore the placeholder
            JOptionPane.showMessageDialog(this, "Enter an Appointment ID to search."); return;
        }
        try {
            String[] lines = FileManager.readLines(APPOINTMENTS_FILE);
            String[] found = null;
            for (String line : lines) {
                if (line == null) continue;
                String[] p = line.split(",");
                // file: apptId,patientId,doctorId,nurseId,date,time,appointType,status,notes
                if (p.length >= 8 && p[0].equalsIgnoreCase(id)) { found = p; break; }
            }
            if (found == null) {
                JOptionPane.showMessageDialog(this, "Appointment not found."); return;
            }
            
            // Hide the misaligned dynamic labels
            lblPatient.setText("");
            lblDate.setText("");
            lblTime.setText("");
            lblDoctor.setText("");
            
            // Append data directly into the neatly stacked title labels to fix visual mismatch
            jLabel1.setText("Patient Name:  " + patientName(found[1]));
            jLabel2.setText("Date:  " + found[4]);
            jLabel3.setText("Time:  " + found[5]);
            jLabel4.setText("Doctor:  " + doctorName(found[2]));
            
            cmbStatus.setSelectedItem(found[7]);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Could not read appointments: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String id = txtApptId.getText().trim();
        if (ValidationUtil.isNullOrEmpty(id) || id.equalsIgnoreCase("Enter Appt ID...")) {
            JOptionPane.showMessageDialog(this, "Search a valid appointment first."); return;
        }
        String newStatus = cmbStatus.getSelectedItem().toString();
        try {
            String[] lines = FileManager.readLines(APPOINTMENTS_FILE);
            boolean found = false;
            for (int i = 0; i < lines.length; i++) {
                if (lines[i] == null) continue;
                String[] p = lines[i].split(",");
                if (p.length >= 8 && p[0].equalsIgnoreCase(id)) {
                    p[7] = newStatus;   // status is the 8th field
                    String notes = (p.length > 8) ? p[8] : "";
                    lines[i] = p[0] + "," + p[1] + "," + p[2] + "," + p[3] + ","
                                 + p[4] + "," + p[5] + "," + p[6] + "," + p[7] + (notes.isEmpty() ? "" : "," + notes);
                    found = true;
                }
            }
            if (found) {
                FileManager.writeLines(APPOINTMENTS_FILE, lines);
                JOptionPane.showMessageDialog(this, "Status updated to " + newStatus);
                txtApptId.setText("Enter Appt ID...");
                jLabel1.setText("Patient Name:");
                jLabel2.setText("Date:");
                jLabel3.setText("Time:");
                jLabel4.setText("Doctor:");
                cmbStatus.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(this, "Appointment not found.");
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Could not save status: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new clinicmanagementsystem.gui.NurseDashboardGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new UpdateAppointmentStatus().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txtApptId;
    // End of variables declaration//GEN-END:variables
}
