/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicmanagementsystem.gui.receptionist;

/**
 *
 * @author Joey
 */
import clinicmanagementsystem.gui.ReceptionistDashboardGUI;
import java.io.PrintWriter;
import java.io.File;
import java.util.Scanner;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CollectPayment extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CollectPayment.class.getName());

    public CollectPayment() {
        initComponents();
        clinicmanagementsystem.util.UIUtils.styleButtons(this);
        loadPayments();
    }

    private boolean validateInput() {
        if (txtPaymentID.getText().trim().isEmpty() ||
            txtAppointmentID.getText().trim().isEmpty() ||
            txtPatientID.getText().trim().isEmpty() ||
            txtPatientName.getText().trim().isEmpty() ||
            txtDate.getText().trim().isEmpty() ||
            txtAmount.getText().trim().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "All fields are required.");
            return false;
        }

        if (!txtDate.getText().trim().matches("^\\d{4}-\\d{2}-\\d{2}$")) {
            JOptionPane.showMessageDialog(this, "Date must be in YYYY-MM-DD format.");
            return false;
        }

        try {
            double amount = Double.parseDouble(txtAmount.getText().trim());
            if (amount < 0) {
                JOptionPane.showMessageDialog(this, "Amount cannot be negative.");
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Amount must be a valid number.");
            return false;
        }

        return true;
    }

    private void loadPayments() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        try {
            BufferedReader br = new BufferedReader(
                    new FileReader("src/clinicmanagementsystem/data/payments.txt")
            );

            String line;

            while ((line = br.readLine()) != null) {
                if (line.toLowerCase().startsWith("paymentid")) {
                    continue;
                }
                if (line.trim().isEmpty()) {
                    continue;
                }

                String[] data = line.split(",", -1);
                String[] paddedData = new String[8];
                for(int i=0; i<8; i++) {
                    paddedData[i] = (i < data.length) ? data[i] : "";
                }
                model.addRow(paddedData);
            }

            br.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clearFields() {
        txtPaymentID.setText("");
        txtAppointmentID.setText("");
        txtPatientID.setText("");
        txtPatientName.setText("");
        txtDate.setText("");
        txtAmount.setText("");

        cmbPaymentMethod.setSelectedIndex(0);
        cmbPaymentStatus.setSelectedIndex(0);
        jTable1.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPaymentID = new javax.swing.JTextField();
        txtPatientID = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        txtAppointmentID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        cmbPaymentMethod = new javax.swing.JComboBox<>();
        cmbPaymentStatus = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PaymentID");

        jLabel2.setText("PatientID");

        jLabel3.setText("Amount");

        jLabel4.setText("PatientName");

        jLabel5.setText("PaymentMethod");

        jLabel6.setText("Payment Status");

        txtPaymentID.addActionListener(this::txtPaymentIDActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment ID", "Appointment ID", "Patient ID", "Patient Name", "Date", "Amount", "Payment Method", "Payment Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnadd.setText("Add");
        btnadd.addActionListener(this::btnaddActionPerformed);

        btnback.setText("Back");
        btnback.addActionListener(this::btnbackActionPerformed);

        btndelete.setText("Delete");
        btndelete.addActionListener(this::btndeleteActionPerformed);

        btnsearch.setText("Search");
        btnsearch.addActionListener(this::btnsearchActionPerformed);

        btnupdate.setText("Update");
        btnupdate.addActionListener(this::btnupdateActionPerformed);

        jLabel7.setText("Appointment ID");

        txtPatientName.addActionListener(this::txtPatientNameActionPerformed);

        jLabel8.setText("Date");

        cmbPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card", "Online Transfer" }));
        cmbPaymentMethod.addActionListener(this::cmbPaymentMethodActionPerformed);

        cmbPaymentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paid", "Unpaid" }));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CollectPayment");

        clearBtn.setText("Clear");
        clearBtn.addActionListener(this::clearBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPaymentID)
                                            .addComponent(txtPatientID)
                                            .addComponent(txtAppointmentID, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                            .addComponent(txtPatientName))))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAmount)
                                    .addComponent(txtDate)
                                    .addComponent(cmbPaymentMethod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbPaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnadd)
                                .addGap(18, 18, 18)
                                .addComponent(btnupdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btndelete)
                                .addGap(16, 16, 16)
                                .addComponent(btnsearch)
                                .addGap(18, 18, 18)
                                .addComponent(clearBtn)
                                .addGap(28, 28, 28)))
                        .addComponent(btnback)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtPaymentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtAppointmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbPaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnadd)
                        .addComponent(btnback)
                        .addComponent(btndelete)
                        .addComponent(btnupdate)
                        .addComponent(btnsearch))
                    .addComponent(clearBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaymentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentIDActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        if (!validateInput()) {
            return;
        }

        String paymentID = txtPaymentID.getText().trim();
        
        // Prevent duplicate Payment IDs
        try (BufferedReader br = new BufferedReader(new FileReader("src/clinicmanagementsystem/data/payments.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.trim().isEmpty()) continue;
                String[] data = line.split(",");
                if (data[0].equalsIgnoreCase(paymentID)) {
                    JOptionPane.showMessageDialog(this, "Payment ID already exists.");
                    return;
                }
            }
        } catch (Exception e) {
            // file might not exist yet
        }

        try {
            BufferedWriter bw = new BufferedWriter(
                    new FileWriter("src/clinicmanagementsystem/data/payments.txt", true)
            );

            String data = txtPaymentID.getText().trim() + ","
                    + txtAppointmentID.getText().trim() + ","
                    + txtPatientID.getText().trim() + ","
                    + txtPatientName.getText().trim() + ","
                    + txtDate.getText().trim() + ","
                    + txtAmount.getText().trim() + ","
                    + cmbPaymentMethod.getSelectedItem().toString() + ","
                    + cmbPaymentStatus.getSelectedItem().toString();

            bw.write(data);
            bw.newLine();
            bw.close();

            JOptionPane.showMessageDialog(this, "Payment collected successfully!");

            loadPayments();
            clearFields();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        ReceptionistDashboardGUI dashboard = new ReceptionistDashboardGUI();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();

        if (row == -1 || jTable1.getValueAt(row, 0) == null) {
            return;
        }

        txtPaymentID.setText(jTable1.getValueAt(row, 0) != null ? jTable1.getValueAt(row, 0).toString() : "");
        txtAppointmentID.setText(jTable1.getValueAt(row, 1) != null ? jTable1.getValueAt(row, 1).toString() : "");
        txtPatientID.setText(jTable1.getValueAt(row, 2) != null ? jTable1.getValueAt(row, 2).toString() : "");
        txtPatientName.setText(jTable1.getValueAt(row, 3) != null ? jTable1.getValueAt(row, 3).toString() : "");
        txtDate.setText(jTable1.getValueAt(row, 4) != null ? jTable1.getValueAt(row, 4).toString() : "");
        txtAmount.setText(jTable1.getValueAt(row, 5) != null ? jTable1.getValueAt(row, 5).toString() : "");
        
        Object methodObj = jTable1.getValueAt(row, 6);
        if (methodObj != null && !methodObj.toString().isEmpty()) cmbPaymentMethod.setSelectedItem(methodObj.toString());
        
        Object statusObj = jTable1.getValueAt(row, 7);
        if (statusObj != null && !statusObj.toString().isEmpty()) cmbPaymentStatus.setSelectedItem(statusObj.toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        String paymentID = txtPaymentID.getText().trim();
        if (paymentID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a Payment to delete.");
            return;
        }

        try {
            File inputFile = new File("src/clinicmanagementsystem/data/payments.txt");
            File tempFile = new File("src/clinicmanagementsystem/data/temp.txt");

            Scanner scanner = new Scanner(inputFile);
            PrintWriter writer = new PrintWriter(tempFile);
            boolean found = false;

            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                if (line.trim().isEmpty()) continue;

                if (line.startsWith(paymentID + ",")) {
                    found = true;
                } else {
                    writer.println(line);
                }
            }

            scanner.close();
            writer.close();

            if (found) {
                inputFile.delete();
                tempFile.renameTo(inputFile);
                JOptionPane.showMessageDialog(this, "Payment deleted successfully!");
                loadPayments();
                clearFields();
            } else {
                tempFile.delete();
                JOptionPane.showMessageDialog(this, "Payment ID not found.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        String searchID = txtPaymentID.getText().trim();
        if (searchID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Payment ID to search.");
            loadPayments();
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        try {
            BufferedReader br = new BufferedReader(
                    new FileReader("src/clinicmanagementsystem/data/payments.txt")
            );

            String line;
            boolean found = false;

            while ((line = br.readLine()) != null) {
                if (line.toLowerCase().startsWith("paymentid")) continue;
                if (line.trim().isEmpty()) continue;

                String[] data = line.split(",", -1);

                if (data[0].equalsIgnoreCase(searchID)) {
                    String[] paddedData = new String[8];
                    for(int i=0; i<8; i++) {
                        paddedData[i] = (i < data.length) ? data[i] : "";
                    }
                    model.addRow(paddedData);
                    
                    txtPaymentID.setText(paddedData[0]);
                    txtAppointmentID.setText(paddedData[1]);
                    txtPatientID.setText(paddedData[2]);
                    txtPatientName.setText(paddedData[3]);
                    txtDate.setText(paddedData[4]);
                    txtAmount.setText(paddedData[5]);
                    if (!paddedData[6].isEmpty()) cmbPaymentMethod.setSelectedItem(paddedData[6]);
                    if (!paddedData[7].isEmpty()) cmbPaymentStatus.setSelectedItem(paddedData[7]);

                    found = true;
                    break;
                }
            }

            br.close();

            if (!found) {
                JOptionPane.showMessageDialog(this, "Payment not found.");
                loadPayments();
                clearFields();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        if (!validateInput()) {
            return;
        }

        String paymentID = txtPaymentID.getText().trim();

        try {
            File inputFile = new File("src/clinicmanagementsystem/data/payments.txt");
            File tempFile = new File("src/clinicmanagementsystem/data/temp.txt");

            Scanner scanner = new Scanner(inputFile);
            PrintWriter writer = new PrintWriter(tempFile);
            boolean found = false;

            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                if (line.trim().isEmpty()) continue;

                if (line.startsWith(paymentID + ",")) {

                    String updatedData = txtPaymentID.getText().trim() + ","
                            + txtAppointmentID.getText().trim() + ","
                            + txtPatientID.getText().trim() + ","
                            + txtPatientName.getText().trim() + ","
                            + txtDate.getText().trim() + ","
                            + txtAmount.getText().trim() + ","
                            + cmbPaymentMethod.getSelectedItem().toString() + ","
                            + cmbPaymentStatus.getSelectedItem().toString();

                    writer.println(updatedData);
                    found = true;
                } else {
                    writer.println(line);
                }
            }

            scanner.close();
            writer.close();

            if (found) {
                inputFile.delete();
                tempFile.renameTo(inputFile);
                JOptionPane.showMessageDialog(this, "Payment updated successfully!");
                loadPayments();
                clearFields();
            } else {
                tempFile.delete();
                JOptionPane.showMessageDialog(this, "Payment ID not found.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void cmbPaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaymentMethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPaymentMethodActionPerformed

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        loadPayments();
        clearFields();
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CollectPayment().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton clearBtn;
    private javax.swing.JComboBox<String> cmbPaymentMethod;
    private javax.swing.JComboBox<String> cmbPaymentStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtAppointmentID;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPaymentID;
    // End of variables declaration//GEN-END:variables
}
