/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicmanagementsystem.gui.receptionist;

import clinicmanagementsystem.gui.ReceptionistDashboardGUI;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import java.io.FileWriter;
import java.io.BufferedWriter;

public class GenerateReceiptGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GenerateReceiptGUI.class.getName());
    private DefaultTableModel model = new DefaultTableModel();
    private String[] columnList = {"Payment ID", "Appointment ID", "Patient ID", "Patient Name", "Date", "Amount", "Method", "Status"};

    /**
     * Creates new form GenerateReceiptGUI
     */
    public GenerateReceiptGUI() {
        initComponents();
        clinicmanagementsystem.util.UIUtils.styleButtons(this);
        txtReceipt.setEditable(false);
        model.setColumnIdentifiers(columnList);
        jTable1.setModel(model);
        loadPayments();
        
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row == -1) return;
        
        String paymentID = jTable1.getValueAt(row, 0).toString();
        txtPaymentID.setText(paymentID);
        btnSearchActionPerformed(null);
    }

    private void loadPayments() {
        model.setRowCount(0);
        try {
            BufferedReader br = new BufferedReader(new FileReader("src/clinicmanagementsystem/data/payments.txt"));
            String line;
            while ((line = br.readLine()) != null) {
                if (line.toLowerCase().startsWith("paymentid")) continue;
                if (line.trim().isEmpty()) continue;
                
                String[] data = line.split(",", -1);
                if (data.length >= 8 && data[7].equalsIgnoreCase("Paid")) {
                    model.addRow(data);
                }
            }
            br.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPaymentID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReceipt = new javax.swing.JTextArea();
        btnSearch = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        printBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Payment ID");

        jLabel7.setText("Receipt Preview");

        txtReceipt.setColumns(20);
        txtReceipt.setRows(5);
        jScrollPane1.setViewportView(txtReceipt);

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnclear.setText("Clear");
        btnclear.addActionListener(this::btnclearActionPerformed);

        btnback.setText("Back");
        btnback.addActionListener(this::btnbackActionPerformed);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Generate Receipt");

        jTable1.setModel(model);
        jScrollPane2.setViewportView(jTable1);

        printBtn.setText("Print");
        printBtn.addActionListener(this::printBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(btnback)
                                .addGap(59, 59, 59)
                                .addComponent(btnclear))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPaymentID, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSearch))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(printBtn)))))
                        .addGap(217, 217, 217)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(printBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtPaymentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSearch)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback)
                    .addComponent(btnclear))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        ReceptionistDashboardGUI dashboard = new ReceptionistDashboardGUI();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtPaymentID.setText("");
        txtReceipt.setText("");
        jTable1.clearSelection();
        loadPayments();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchID = txtPaymentID.getText().trim();
        boolean found = false;

        try {
            BufferedReader br = new BufferedReader(
                    new FileReader("src/clinicmanagementsystem/data/payments.txt")
            );

            String line;

            while ((line = br.readLine()) != null) {
                if (line.toLowerCase().startsWith("paymentid")) continue;
                if (line.trim().isEmpty()) continue;

                String[] data = line.split(",", -1);

                if (data.length >= 8 && data[0].trim().equalsIgnoreCase(searchID)) {

                    String paymentID = data[0];
                    String appointmentID = data[1];
                    String patientID = data[2];
                    String patientName = data[3];
                    String date = data[4];
                    String amount = data[5];
                    String paymentMethod = data[6];
                    String paymentStatus = data[7];

                    if (!paymentStatus.equalsIgnoreCase("Paid")) {
                        JOptionPane.showMessageDialog(this,
                                "Receipt can only be generated for Paid payments.");
                        txtReceipt.setText("");
                        br.close();
                        return;
                    }

                    txtReceipt.setText(
                            "========== CLINIC PAYMENT RECEIPT ==========\n"
                            + "Payment ID: " + paymentID + "\n"
                            + "Appointment ID: " + appointmentID + "\n"
                            + "Patient ID: " + patientID + "\n"
                            + "Patient Name: " + patientName + "\n"
                            + "Date: " + date + "\n"
                            + "Amount: RM " + amount + "\n"
                            + "Payment Method: " + paymentMethod + "\n"
                            + "Payment Status: " + paymentStatus + "\n"
                            + "==========================================="
                    );

                    found = true;
                    break;
                }
            }

            br.close();

            if (!found) {
                JOptionPane.showMessageDialog(this, "Payment record not found.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        String receiptContent = txtReceipt.getText();
        if (receiptContent.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please generate a receipt first.");
            return;
        }
        
        String paymentID = txtPaymentID.getText().trim();
        if (paymentID.isEmpty()) paymentID = "Unknown";
        
        String filePath = "src/clinicmanagementsystem/data/Receipt_" + paymentID + ".txt";
        
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(filePath));
            bw.write(receiptContent);
            bw.close();
            JOptionPane.showMessageDialog(this, "Receipt successfully saved to data folder!\nFile: Receipt_" + paymentID + ".txt");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving receipt: " + e.getMessage());
        }
    }//GEN-LAST:event_printBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GenerateReceiptGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton printBtn;
    private javax.swing.JTextField txtPaymentID;
    private javax.swing.JTextArea txtReceipt;
    // End of variables declaration//GEN-END:variables
}
