package clinicmanagementsystem.gui.patient;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class MedicalRecords extends javax.swing.JDialog {
    
    private String patientId;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MedicalRecords.class.getName());

    /**
     * Creates new form MedicalRecords
     */
    public MedicalRecords(java.awt.Frame parent, boolean modal, String patientId) {
        super(parent, modal);
        this.patientId = patientId;
        initComponents();
        loadMedicalRecords(null); // အစမှာ filter မလုပ်ဘဲ record အားလုံးပြမယ်
    }
    
private void loadMedicalRecords(String dateFilter) {

    javax.swing.table.DefaultTableModel model = 
        (javax.swing.table.DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    
    String searchDate = "";
    if (dateFilter != null) {
        searchDate = dateFilter.trim();
    }

    String filePath = "src/clinicmanagementsystem/data/medical_records.txt";

    try {
        java.io.BufferedReader br = new java.io.BufferedReader(
            new java.io.FileReader(filePath));
        String line;

        while ((line = br.readLine()) != null) {
            if (line.trim().isEmpty()) continue;

            String[] parts = line.split(",");
            if (parts.length < 7) continue;

            String recordId      = parts[0].trim(); // MR001
            String filePatientId = parts[1].trim(); // P001
            String doctor        = parts[2].trim(); // U002
            String diagnosis     = parts[3].trim();
            String treatment     = parts[4].trim();
            String notes         = parts[5].trim();
            String recordDate    = parts[6].trim();
            

            // Login လုပ်ထားတဲ့ patient ရဲ့ data ပဲထည့်မယ်
            if (filePatientId.equals(patientId) == false) {
                continue;
            }
            if (searchDate.isEmpty() == false) {
                if (recordDate.contains(searchDate) == false) {
                continue;
            }
        }
            // Table columns: Record ID, Doctor, Diagnosis, Treatment, Doctor Notes, Date
            Object[] row = {recordId, doctor, diagnosis, treatment, notes, recordDate};
            model.addRow(row);
        }
        br.close();
        if (searchDate.isEmpty() == false && model.getRowCount() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this,
        "No records found for date: " + searchDate);
}

    } catch (java.io.IOException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error loading records: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblFilterDate = new javax.swing.JLabel();
        txtFilterDate = new javax.swing.JTextField();
        btnFilter = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        setType(java.awt.Window.Type.POPUP);

        lblTitle.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTitle.setText("View Medical Records");
        lblTitle.setPreferredSize(new java.awt.Dimension(250, 30));

        lblFilterDate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblFilterDate.setText("Filter by Date:");
        lblFilterDate.setPreferredSize(new java.awt.Dimension(90, 25));

        txtFilterDate.setPreferredSize(new java.awt.Dimension(150, 25));
        txtFilterDate.addActionListener(this::txtFilterDateActionPerformed);

        btnFilter.setText("Filter");
        btnFilter.setPreferredSize(new java.awt.Dimension(80, 25));
        btnFilter.addActionListener(this::btnFilterActionPerformed);

        btnBack.setText("Back");
        btnBack.setPreferredSize(new java.awt.Dimension(80, 25));
        btnBack.addActionListener(this::btnBackActionPerformed);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(520, 280));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Record ID", "Doctor", "Diagnosis", "Treatment", "Doctor Notes", "Date"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setRowHeight(24);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(90);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(75);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(180);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(180);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(180);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(130);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFilterDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(txtFilterDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFilterDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFilterDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtFilterDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterDateActionPerformed
         String dateText = txtFilterDate.getText();
        loadMedicalRecords(dateText);
    }//GEN-LAST:event_txtFilterDateActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        String dateText = txtFilterDate.getText();
        loadMedicalRecords(dateText);
    }//GEN-LAST:event_btnFilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                String currentId = clinicmanagementsystem.util.SessionManager.getCurrentPatientId();
                MedicalRecords dialog = new MedicalRecords(new javax.swing.JFrame(), true, currentId != null ? currentId : "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFilter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFilterDate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtFilterDate;
    // End of variables declaration//GEN-END:variables
}
