/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicmanagementsystem.gui;

import clinicmanagementsystem.gui.nurse.AppointmentForm;
import clinicmanagementsystem.gui.nurse.RosterForm;
import clinicmanagementsystem.gui.nurse.StatusForm;
import clinicmanagementsystem.gui.nurse.VitalsForm;
import clinicmanagementsystem.util.SessionManager;

/**
 *
 * @author PC
 */
public class NurseDashboardGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NurseDashboardGUI.class.getName());

    /**
     * Creates new form NurseDashboard
     */
    public NurseDashboardGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRoaster = new javax.swing.JButton();
        btnAppointments = new javax.swing.JButton();
        btnVitals = new javax.swing.JButton();
        btnStatus = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRoaster.setText("View My Roster");
        btnRoaster.addActionListener(this::btnRoasterActionPerformed);

        btnAppointments.setText("View Assigned Appointments");
        btnAppointments.addActionListener(this::btnAppointmentsActionPerformed);

        btnVitals.setText("Record Patient Vitals");
        btnVitals.addActionListener(this::btnVitalsActionPerformed);

        btnStatus.setText("Update Appointment Status");
        btnStatus.addActionListener(this::btnStatusActionPerformed);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        jButton1.setText("Exit");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(50, 50, 50)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnVitals, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRoaster, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnAppointments)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnRoaster)
                .addGap(18, 18, 18)
                .addComponent(btnVitals)
                .addGap(18, 18, 18)
                .addComponent(btnStatus)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(jButton1))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRoasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoasterActionPerformed
        new RosterForm().setVisible(true);
    }//GEN-LAST:event_btnRoasterActionPerformed

    private void btnAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentsActionPerformed
        new AppointmentForm().setVisible(true);
    }//GEN-LAST:event_btnAppointmentsActionPerformed

    private void btnVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitalsActionPerformed
        new VitalsForm().setVisible(true);
    }//GEN-LAST:event_btnVitalsActionPerformed

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        new StatusForm().setVisible(true);
    }//GEN-LAST:event_btnStatusActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        SessionManager.clear();
        new LoginGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new NurseDashboardGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointments;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRoaster;
    private javax.swing.JButton btnStatus;
    private javax.swing.JButton btnVitals;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
