/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicmanagementsystem.gui;

import clinicmanagementsystem.gui.receptionist.AssignDoctorAndNurseGUI;
import clinicmanagementsystem.gui.receptionist.CollectPayment;
import clinicmanagementsystem.gui.receptionist.GenerateReceiptGUI;
import clinicmanagementsystem.gui.receptionist.ManageAppointmentsGUI;
import clinicmanagementsystem.gui.receptionist.ManagePatientsGUI;

/**
 *
 * @author Acer
 */
public class ReceptionistDashboardGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReceptionistDashboardGUI.class.getName());

    /**
     * Creates new form ReceptionistDashboardGUI
     */
    public ReceptionistDashboardGUI() {
        initComponents();
        clinicmanagementsystem.util.UIUtils.styleButtons(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        manageAppointmentBtn = new javax.swing.JButton();
        managePatientBtn = new javax.swing.JButton();
        assignDoctorAndNurseBtn = new javax.swing.JButton();
        collectPaymetBtn = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        generateReceiptBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Exit");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        manageAppointmentBtn.setText(" Manage Appointments");
        manageAppointmentBtn.addActionListener(this::manageAppointmentBtnActionPerformed);

        managePatientBtn.setText("ManagePatients");
        managePatientBtn.addActionListener(this::managePatientBtnActionPerformed);

        assignDoctorAndNurseBtn.setText(" Assign Doctor and Nurse");
        assignDoctorAndNurseBtn.addActionListener(this::assignDoctorAndNurseBtnActionPerformed);

        collectPaymetBtn.setText("Collect Payment");
        collectPaymetBtn.addActionListener(this::collectPaymetBtnActionPerformed);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        generateReceiptBtn.setText("Generate Receipt");
        generateReceiptBtn.addActionListener(this::generateReceiptBtnActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Reception Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(managePatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(manageAppointmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(assignDoctorAndNurseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1)
                            .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generateReceiptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(collectPaymetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(managePatientBtn)
                .addGap(18, 18, 18)
                .addComponent(manageAppointmentBtn)
                .addGap(18, 18, 18)
                .addComponent(assignDoctorAndNurseBtn)
                .addGap(18, 18, 18)
                .addComponent(collectPaymetBtn)
                .addGap(16, 16, 16)
                .addComponent(generateReceiptBtn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnLogout))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void manageAppointmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAppointmentBtnActionPerformed
        ManageAppointmentsGUI ma = new ManageAppointmentsGUI();
        ma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageAppointmentBtnActionPerformed

    private void managePatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePatientBtnActionPerformed
        ManagePatientsGUI mp = new ManagePatientsGUI();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_managePatientBtnActionPerformed

    private void assignDoctorAndNurseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignDoctorAndNurseBtnActionPerformed
        AssignDoctorAndNurseGUI mp = new AssignDoctorAndNurseGUI();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_assignDoctorAndNurseBtnActionPerformed

    private void collectPaymetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectPaymetBtnActionPerformed
        CollectPayment cp = new CollectPayment();
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_collectPaymetBtnActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void generateReceiptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReceiptBtnActionPerformed
        GenerateReceiptGUI gr = new GenerateReceiptGUI();
        gr.setVisible(true);
        this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_generateReceiptBtnActionPerformed
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReceptionistDashboardGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignDoctorAndNurseBtn;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton collectPaymetBtn;
    private javax.swing.JButton generateReceiptBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageAppointmentBtn;
    private javax.swing.JButton managePatientBtn;
    // End of variables declaration//GEN-END:variables
}
